uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents/relreases/latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_length: 8
  rx_checksum: add
  tx_checksum: add

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

light:
  - platform: uartex
    name: "Light 1"
    state: 
      data: [0xB0, 0x00, 0x01]
      mask: [0xB0, 0x00, 0xFF]
    state_on:
      offset: 1
      data: [0x01]
    state_off:
      offset: 1
      data: [0x00]
    command_on: 
      data: [0x31, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x01, 0x01]
    command_off:
      data: [0x31, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0xB1, 0x00, 0x01]

climate:
  - platform: uartex
    name: "Heater 1"
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x80, 0x00, 0x01]
      mask: [0x80, 0x00, 0xFF]
    state_temperature_current:
      offset: 3
      length: 1
      precision: 0
    state_temperature_target:
      offset: 4
      length: 1
      precision: 0
    state_off:
      offset: 1
      data: [0x80]
    state_heat:
      offset: 1
      data: [0x83]
    command_off:
      data: [0x04, 0x01, 0x04, 0x00, 0x00, 0x00, 0x00]
      ack: [0x84, 0x80, 0x01]
    command_heat:
      data: [0x04, 0x01, 0x04, 0x81, 0x00, 0x00, 0x00]
      ack: [0x84, 0x81, 0x01]
    command_temperature: !lambda |-
      float target = x;
      return {{0x04, 0x01, 0x03, (uint8_t)target, 0x00, 0x00, 0x00},{0x84, (uint8_t)target, 0x01}}

valve:
  - platform: uartex
    name: "Gas Valve"
    state: 
      data: [0x90]
      mask: [0x90]
    state_open:
      offset: 1
      data: [0xA0, 0xA0]
    state_closed:
      offset: 1
      data: [0x08, 0x08]
      mask: [0x0F, 0x0F]
    command_close:
      data: [0x11, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00]
      ack: [0x91, 0x58, 0x58]

sensor:
  - platform: uartex
    name: "Elevator Floors"
    icon: "mdi:elevator"
    state: 
      data: [0x23]
      mask: [0xFF]
    state_number:
      offset: 3
      length: 1
      precision: 0

button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x22, 0x01, 0x40, 0x07, 0x00, 0x00, 0x00]
      ack: [0xA2]

