esp8266:
  board: d1_mini
    
sensor:
  - platform: pulse_counter
    pin: GPIO4
    name: "Geiger Counter"
    id: "geiger_counter"
    unit_of_measurement: 'CPM'
    update_interval: 20s
    on_raw_value:
      - sensor.template.publish:
          id: radiation_level
          state: !lambda 'return x * 0.0075;'
    on_value_range:
      - below: 1
        then: 
          - switch.turn_on: backlight
  - platform: template
    name: "Radiation Level"
    id: "radiation_level"
    unit_of_measurement: 'µSv/h'
    icon: mdi:radioactive
    accuracy_decimals: 2
    update_interval: 20s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: false
    name: "Backlight Status"
    id: backlight_status
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms

switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: true
    id: backlight
    name: "Backlight"
    # If ESP reboots, do not attempt to restore switch state
    restore_mode: always off
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: backlight