<<: !include ../secrets.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${node_name} Button"
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: id_switch
  - platform: status
    name: "${node_name} Status"
    
# Example configuration entry
switch:
  - platform: gpio
    id: id_switch
    pin: GPIO5
    name: "${node_name} Switch"
    
output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO4
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${node_name} Blue LED"
    output: blue_led
    
    
