sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "${friendly_name} Temperature" 
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
    humidity:
      name: "${friendly_name} Humidity" 
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
    update_interval: 5min
    