sensor:
  - platform: internal_temperature
    name: "${name} Internal Temperature"
    friendly_name: "${friendly_name} Internal Temperature"    
    update_interval: 5min
    filters:
      - filter_out: nan
      - heartbeat: 15s
      - sliding_window_moving_average:
          window_size: 20
          send_every: 1
          send_first_at: 1
