# uart:
#   baud_rate: 9600
#   data_bits: 8
#   parity: NONE
#   stop_bits: 1
#   rx_pin: GPIO22
#   tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents/relreases/latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_header: [0xAA, 0x55]
  rx_footer: [0x0D, 0x0D]
  tx_header: [0xAA, 0x55]
  tx_footer: [0x0D, 0x0D]

  rx_checksum: add
  tx_checksum: add

  on_write: !lambda |-
    // @param: const uint8_t *data, const unsigned short len
    std::string res = "[W]" + to_hex_string(data, len);
    if (res == id(id_data_log).state) res += '.';
    id(id_data_log).publish_state(res.c_str());

  on_read: !lambda |-
    // @param: const uint8_t *data, const unsigned short len
    std::string res = "[R]" + to_hex_string(data, len);
    if (res == id(id_data_log).state) res += '.';
    id(id_data_log).publish_state(res.c_str());

text_sensor:
  - platform: template
    name: "Kocom Data Log"
    id: id_data_log
    icon: "mdi:math-log" 


light:
  #Room0
  - platform: uartex
    name: "Kocom Room 0 Light 1"
    id: room_0_light_1
    state: [0x30, 0xdc, 0x00, 0x0e, 0x00]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_0_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_0_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    #command_state: [0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    #update_interval: 300s

  - platform: uartex
    name: "Kocom Room 0 Light 2"
    id: room_0_light_2
    state: [0x30, 0xdc, 0x00, 0x0e, 0x00]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_0_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_0_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room1
  - platform: uartex
    name: "Kocom Room 1 Light 1"
    id: room_1_light_1
    state: [0x30, 0xdc, 0x00, 0x0e, 0x01]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_1_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_1_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Kocom Room 1 Light 2"
    id: room_1_light_2
    state: [0x30, 0xdc, 0x00, 0x0e, 0x01]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_1_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_1_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room2
  - platform: uartex
    name: "Kocom Room 2 Light 1"
    id: room_2_light_1
    state: [0x30, 0xdc, 0x00, 0x0e, 0x02]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_2_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_2_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Kocom Room 2 Light 2"
    id: room_2_light_2
    state: [0x30, 0xdc, 0x00, 0x0e, 0x02]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_2_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_2_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room3
  - platform: uartex
    name: "Kocom Room 3 Light 1"
    id: room_3_light_1
    state: [0x30, 0xdc, 0x00, 0x0e, 0x03]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_3_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_3_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Kocom Room 3 Light 2"
    id: room_3_light_2
    state: [0x30, 0xdc, 0x00, 0x0e, 0x03]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_3_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_3_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};



climate:
  #Room0
  - platform: uartex
    name: "Kocom Room 0 Heater"
    id: room_0_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: [0x30, 0xdc, 0x00, 0x36, 0x00]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |-
      float target = id(room_0_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_0_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    #command_state: [0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    #update_interval: 300s

  #Room1
  - platform: uartex
    name: "Kocom Room 1 Heater"
    id: room_1_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: [0x30, 0xdc, 0x00, 0x36, 0x01]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |- 
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};

  #Room2
  - platform: uartex
    name: "Kocom Room 2 Heater"
    id: room_2_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: [0x30, 0xdc, 0x00, 0x36, 0x02]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};

  #Room3
  - platform: uartex
    name: "Kocom Room 3 Heater"
    id: room_3_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: [0x30, 0xdc, 0x00, 0x36, 0x03]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |-
      float target = id(room_3_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_3_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};


sensor:
  - platform: uartex
    name: Kocom Elevator Floors
    icon: "mdi:elevator"
    state: [0x30, 0xbc, 0x00, 0x44, 0x00]
    state_number:
      offset: 9
      length: 1
      precision: 0

  - platform: uartex
    name: Kocom Room 0 Temperature
    unit_of_measurement: '°C'
    icon: "mdi:coolant-temperature"
    state: [0x30, 0xdc, 0x00, 0x36, 0x00]
    state_number:
      offset: 12
      length: 1
      precision: 0

  - platform: uartex
    name: Kocom Room 1 Temperature
    unit_of_measurement: '°C'
    icon: "mdi:coolant-temperature"
    state: [0x30, 0xdc, 0x00, 0x36, 0x01]
    state_number:
      offset: 12
      length: 1
      precision: 0

  - platform: uartex
    name: Kocom Room 2 Temperature
    unit_of_measurement: '°C'
    icon: "mdi:coolant-temperature"
    state: [0x30, 0xdc, 0x00, 0x36, 0x02]
    state_number:
      offset: 12
      length: 1
      precision: 0

  - platform: uartex
    name: Kocom Room 3 Temperature
    unit_of_measurement: '°C'
    icon: "mdi:coolant-temperature"
    state: [0x30, 0xdc, 0x00, 0x36, 0x03]
    state_number:
      offset: 12
      length: 1
      precision: 0

button:
  - platform: uartex
    name: Kocom Elevator Call
    icon: "mdi:elevator"
    command_on: 
      data: [0x30, 0xbc, 0x00, 0x44, 0x00, 0x01, 0x00, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
