binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} Button"
    internal: True
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: id_switch
    
# Example configuration entry
switch:
  - platform: gpio
    id: id_switch
    pin: GPIO5
    name: "${name} Switch"
    restore_mode: RESTORE_DEFAULT_OFF
    
output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO4
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${name} Blue LED"
    output: blue_led
    internal: True
    
    
