name: Update latest Tag Only

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get target commit SHA
        id: get_commit_sha
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let targetSha;
            // release 이벤트로 트리거 된 경우 payload에서 대상 커밋 정보를 사용
            if (context.payload.release) {
              targetSha = context.payload.release.target_commitish;
              console.log("Release event detected. Target commitish:", targetSha);
              // 만약 브랜치 이름인 경우, 해당 브랜치의 최신 커밋 SHA를 가져옴
              if (targetSha.length !== 40) {
                const branchInfo = await github.rest.repos.getBranch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: targetSha
                });
                targetSha = branchInfo.data.commit.sha;
                console.log("Resolved branch to SHA:", targetSha);
              }
            } else {
              // manual trigger일 경우, API를 통해 최신 릴리즈 정보를 가져와서 대상 커밋 정보를 사용
              console.log("No release event payload. Fetching latest release info via API.");
              const latestRelease = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              targetSha = latestRelease.data.target_commitish;
              console.log("Latest release target_commitish:", targetSha);
              if (targetSha.length !== 40) {
                const branchInfo = await github.rest.repos.getBranch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  branch: targetSha
                });
                targetSha = branchInfo.data.commit.sha;
                console.log("Resolved branch to SHA:", targetSha);
              }
            }
            return targetSha;

      - name: Update or Create tag "latest"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // get_commit_sha 스텝에서 리턴한 값을 사용 (실제 커밋 SHA)
            const targetSha = "${{ steps.get_commit_sha.outputs.result }}";
            console.log(`Target SHA for tag 'latest': ${targetSha}`);

            try {
              console.log(`Attempting to update tag 'latest' to commit ${targetSha}`);
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/latest",
                sha: targetSha,
                force: true
              });
              console.log("Tag 'latest' successfully updated.");
            } catch (error) {
              console.log("Tag 'latest' does not exist. Creating tag 'latest'.");
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/latest",
                sha: targetSha,
              });
              console.log("Tag 'latest' successfully created.");
            }
